---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: Introduction to the lab
    - name: module-02
      label: Install System Roles
    - name: module-03
      label: Enable access to the httpd service
    - name: module-04
      label: Open an arbitrary port
    - name: module-05
      label: Configure port forwarding
    - name: module-06
      label: Reset the firewall to default settings
    - name: module-07
      label: Conclusion
tabs:
  - name: ">_ controlnode"
    port: 443
    path: /tty1
    user: root
    host: controlnode
  - name: ">_ rhelvm"
    port: 443
    path: /tty2
    user: root
    host: rhelvm
