The firewall system role can reset all settings to the default
configuration found immediately after Red Hat Enterprise Linux is
installed.

We’ll reset the firewall configuration in the `rhelvm` host.

First, in the `*>_ rhelvm*` terminal, list the
current rules.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
firewall-cmd --list-all
----

.Output
[source,bash,subs="+macros,+attributes",role=execute]
----
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0
  sources:
  services: cockpit dhcpv6-client http ssh
  ports: 9999/tcp
  protocols:
  forward: yes
  masquerade: no
  forward-ports:
        port=9999:proto=tcp:toport=12345:toaddr=
  source-ports:
  icmp-blocks:
  rich rules:
----

In the `*>_ controlnode*` terminal, we’ll create a
new host file called `*reset*`.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
tee -a /root/reset << EOF
all:
  hosts:
    rhelvm.{{ guid }}.internal:
  vars:
    firewall:
      - previous: replaced
EOF
----

From the `*>_ controlnode*` terminal, run the
playbook to reset the firewall rules on the `*rhelvm*` host.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
ansible-playbook -i reset -b firewall.yml
----

.Output
[source,text,subs="+macros,+attributes"]
----
<<< OUTPUT ABRIDGED >>>

TASK [redhat.rhel_system_roles.firewall : Calculate what has changed] ************************************************************
changed: [rhelvm.{{ guid }}.internal]

<<< OUTPUT ABRIDGED >>>

PLAY RECAP *************************************************
rhelvm.{{ guid }}.internal      : ok=9    changed=1    unreachable=0    failed=0    skipped=12   rescued=0    ignored=0
----

When the playbook as stopped running, switch to the `*>_ rhelvm*` terminal and check that the firewall rules have been reset.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
firewall-cmd --list-all
----

.Output
[source,bash,subs="+macros,+attributes",role=execute]
----
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0
  sources:
  services: cockpit dhcpv6-client ssh
  ports:
  protocols:
  forward: yes
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
----

If you want to apply the rules we created in the previous steps of this
lab, run `*ansible-playbook -i hosts -b firewall.yml*` again on the `*>_ controlnode*`
